name: Frank C. Eckert
title: Frank C. Eckert
pygments: true
author:
  name: Frank C. Eckert
  twitter: FrankCEckert
  github: opahk
  linkedin: pub/frank-c-eckert/73/615/584
  google: u/1/107710822840121295757
  xing: FrankC_Eckert
